name: Build-and-test

on: 
  push: 
    branches: [main,staging]
  pull_request: 
    branched: [main,staging]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    strategy: 
      matrix: 
        node-version: [16.x, 17.x, 18.x]

    steps: 
      - uses: actions/checkout@v3
      
      - name: Use node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node_version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.1
        with: 
          version: 6.32.4

      - name: Install deps
        run: pnpm i

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build
      
